import type { Stream, TemplateConfig } from "@yext/pages";
import { dedupeStreamFields } from "src/common/helpers";

/**
 * Required when Knowledge Graph data is used for a template.
 */
export const configBuilder: (
  id?: string,
  filter?: Stream["filter"],
  pageUrlField?: string
) => TemplateConfig = (
  id?: string,
  filter?: Stream["filter"],
  pageUrlField?: string
) => ({
  stream: {
    $id: id || "locations",
    // Specifies the exact data that each generated document will contain. This data is passed in
    // directly as props to the default exported function.
    fields: dedupeStreamFields([
      "id",
      "uid",
      "c_pagesURL",
      "c_pagesURLCabelas",
      "logo",
      "c_meta",
      "name",
      "address",
      "geomodifier",
      "mainPhone",
      "tollFreePhone",
      "emails",
      "yextDisplayCoordinate",
      "description",
      "hours",
      "googlePlaceId",
      "photoGallery",
      "ref_listings.listingUrl",
      "ref_listings.publisher",
      "additionalHoursText",
      "c_additionalHoursUnderRegularHours",
      "services",
      "dm_directoryParents_bassprodirectory.name",
      "dm_directoryParents_bassprodirectory.slug",
      "dm_directoryParents_cabelasdirectory.name",
      "dm_directoryParents_cabelasdirectory.slug",
      "dm_baseEntityCount",
      "slug",
      "timezone",
      "c_geomodifier",
      "c_boatAndATVServiceHeading",
      "c_additionalHoursADMIN",
      "c_additionalHoursLabel3",
      "facebookPageUrl",
      // About Fields
      "c_aboutSection",
      "description",
      // Banner Fields
      "c_bannerSection",
      // Gallery Fields
      "c_gallerySection",
      "photoGallery",
      // Hero Fields
      "c_heroSection",
      // Insights Fields
      "c_insightsSection.title",
      "c_insightsSection.cta",
      "c_insightsSection.insights.title",
      "c_insightsSection.insights.category",
      "c_insightsSection.insights.photo",
      "c_insightsSection.insights.date",
      "c_insightsSection.insights.descriptionLong",
      "c_insightsSection.insights.descriptionShort",
      "c_insightsSection.insights.cta",
      // Nearby Fields
      "c_nearbySection",
      // Promo Fields
      "c_promoSection",
      // Review Fields
      "c_reviewsSection",
      "c_fAQTitle",
      "c_question1",
      "c_question2",
      "c_question3",
      "c_question4",
      "c_question5",
      "c_question6",
      "c_answer1",
      "c_answer2",
      "c_answer3",
      "c_answer4",
      "c_answer5",
      "c_answer6",
      "c_employmentPromoTitle",
      "c_employmentPromoDescription",
      "c_employmentPromoButtonText",
      "c_employmentPromoButtonURl",
      "c_aboutStoreSubhead",
      "c_pagesBusinessDescription",
      "c_promotionImage2",
      "c_categoryTitle",
      "c_category1",
      "c_category2",
      "c_category3",
      "c_category4",
      "c_category5",
      "c_category6",
      "c_category7",
      "c_category8",
      "c_category9",
      "c_promotionCarouselList",
      "c_pickupLabel",
      "c_curbside_pickup",
      "c_shopNowButtonText",
      "c_shopNowButtonURL",
      "c_teamLabel",
      "c_restaurantManager",
      "c_storeManagerTitle3",
      "c_restaurantEmail",
      "c_storeManagerEmailText3",
      "c_tmbcManager",
      "c_tmbcEmail",
      "c_storeManagerTitle2",
      "c_storeManagerEmailText2",
      "c_storeManager",
      "c_storeManagerTitle1",
      "c_storeManagerEmailText1",
      "c_trackerBoatLogo",
      "c_restaurantLogos",
      "c_hoursLabel",
      "c_connectWithUsLabel",
      "c_signUpLinkText",
      "c_formURL",
      "c_salesLabel",
      "c_thisStoreLabel",
      "c_storeServiceList1",
      "c_serviceLabel",
      "c_servicesThisStore",
      "c_boatSalesHoursHeading",
      "c_boatAndATVServiceHours",
      "c_heroImage1",
      "c_pagesMetaDescription",
      "c_pagesMetaTitle",
      // Event Section Fields
      "c_linkedEventEntity.photoGallery",
      "c_linkedEventEntity.name",
      "c_linkedEventEntity.websiteUrl",
      "c_linkedEventEntity.time",
      "c_linkedEventEntity.description",
      "c_linkedEventEntity.c_eventType",
      // Bio Section Fields
      "c_linkedEntity.name",
      "c_linkedEntity.description",
      "c_linkedEntity.c_bioPhoto",
      "c_linkedEntity.c_affiliationsAndCertifications",
      "c_linkedEntity.services",
      "c_staffSectionTitle",
      "c_redirectPagesURL",
      "c_oldPagesURL",
      "c_localPartners",
      "c_localPartnersTitle",
    ]),
    // Defines the scope of entities that qualify for this stream.
    filter: filter || {
      savedFilterIds: ["1370206811"], // default bass pro
    },
    // The entity language profiles that documents will be generated for.
    localization: {
      locales: ["en"],
    },
  },
  pageUrlField: pageUrlField || "c_pagesURL",
});
